#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Get streamlit email from env
STREAMLIT_EMAIL=${STREAMLIT_EMAIL}

# Get the streamlit port
STREAMLIT_PORT=${STREAMLIT_PORT:-8501}

# Activate Streamlit with email
{
  echo $STREAMLIT_EMAIL | streamlit activate
} || {
  echo "Streamlit already activated"
}

# Start Streamlit app
streamlit run \
  --server.port $STREAMLIT_PORT \
  --server.headless true \
  --browser.serverAddress="0.0.0.0" \
  --server.enableCORS false \
  --server.enableXsrfProtection=false \
  --browser.gatherUsageStats false \
  ./src/cqc_lem/streamlit/Home.py
