#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Get streamlit email from env
STREAMLIT_EMAIL=${STREAMLIT_EMAIL}

# Get the streamlit port
STREAMLIT_PORT=${STREAMLIT_PORT:-8501}

# Get the api port
API_PORT=${API_PORT:-8000}

# Activate Streamlit with email
{
  echo $STREAMLIT_EMAIL | streamlit activate
} || {
  echo "Streamlit already activated"
}

# Start Streamlit app
streamlit run --server.port $STREAMLIT_PORT ./src/cqc_lem_streamlit/Home.py &

# Start FASTAPI / Uvicorn
uvicorn src.cqc_lem.api.main:app --reload --host 0.0.0.0 --port $API_PORT

# Keep the container running ???
# tail -f /dev/null