# ngrok-config-template.yml
version: 3

agent:
  authtoken: ${NGROK_AUTH_TOKEN}
  web_addr: 0.0.0.0:${NGROK_UI_PORT}

tunnels:
  lem-app:
    proto: http
    addr: ${API_PORT}
    domain: ${NGROK_CUSTOM_DOMAIN}
  lem-flower:
    proto: http
    addr: ${CELERY_FLOWER_PORT}
    domain: ${NGROK_FLOWER_PREFIX}.${NGROK_FREE_DOMAIN}
  lem-chrome:
    proto: http
    addr: 7900
    domain: ${NGROK_CHROME_PREFIX}.${NGROK_FREE_DOMAIN}
