#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    # TODO: Check on the -A param here
    celery -A cqc_lem.my_celery inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

# TODO: Check on the -A param here
celery --app cqc_lem.my_celery  \
    --broker="${CELERY_BROKER_URL}" \
    flower \
    --broker-api="${CELERY_BROKER_URL}" \
    --logging="DEBUG" \
    --logfile="/app/logs" \
    #--persistent=True \
    --debug=True \
    --db=/var/lib/flower/flowerdb/flower_db \
    #--state_save_interval=5000 \
    #-Q (your queue name)

