#!/bin/bash

set -o errexit
set -o nounset

celery --app cqc_lem.app.my_celery \
  flower \
  --port="${CELERY_FLOWER_PORT}" \
  --address=0.0.0.0 \
  --broker="${CELERY_BROKER_URL}" \
  --broker-api="${CELERY_BROKER_URL}" \
  --logging="INFO" \
  --logfile="/app/logs/flower.log" \
  --state_save_interval="${CELERY_FLOWER_STATE_SAVE_INTERVAL}"
  #--basic_auth=admin:${CELERY_FLOWER_PASSWORD}
