#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery --app cqc_lem.app.my_celery inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

celery --app cqc_lem.app.my_celery \
  --broker="${CELERY_BROKER_URL}" \
  flower \
  --broker-api="${CELERY_BROKER_URL}" \
  --logging="DEBUG" \
  --logfile="/app/logs" \
  --debug=True \
  --state_save_interval=5000 \
  --persistent=True \
  --db=/data/flower.db
  #--basic_auth=admin:${CELERY_FLOWER_PASSWORD} \
  #-Q (your queue name)

