#!/bin/bash

set -o errexit
set -o nounset

celery --app cqc_lem.app.my_celery \
  --broker="${CELERY_BROKER_URL}" \
  flower \
  --port="${CELERY_FLOWER_PORT}" \
  --broker-api="${CELERY_BROKER_URL}" \
  --logging="DEBUG" \
  --logfile="/app/logs" \
  --debug=True &

  #--basic_auth=admin:${CELERY_FLOWER_PASSWORD} \

  #-Q (your queue name)

# Function to check if Celery worker is ready
worker_ready() {
    celery --app cqc_lem.app.my_celery inspect ping
}

# Wait for Celery worker to be ready
until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 5
done
>&2 echo 'Celery workers are available'

# Keep the script running
wait
