#!/bin/bash

set -o errexit
set -o nounset

celery --app cqc_lem.app.my_celery \
  --broker="${CELERY_BROKER_URL}" \
  flower \
  #--broker-api="${CELERY_BROKER_URL}" \
  --logging="DEBUG" \
  --logfile="/app/logs" \
  #--persistent=True \
  --debug=True \
  --db=/data/flower.db
  #--basic_auth=admin:${CELERY_FLOWER_PASSWORD} \
  #--state_save_interval=5000 \
  #-Q (your queue name)

