#!/bin/bash

set -o errexit
set -o nounset

rm -f './celerybeat.pid'

# Purge previous task
echo "Purging previous task"
celery --app cqc_lem.app.my_celery purge -f


# clear the selenium sessions
echo "Clearing selenium sessions"
python -c "from cqc_lem.utilities.selenium_util import clear_sessions; clear_sessions()"

# Start Celery Beat
echo "Starting Celery Beat"
celery --app cqc_lem.app.my_celery beat -l info

