#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Get the api port
API_PORT=${API_PORT:-8000}

# Start FASTAPI / Uvicorn
uvicorn src.cqc_lem.api.main:app --reload --host 0.0.0.0 --port $API_PORT