#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Get the api port
API_PORT=${API_PORT:-8000}

# TODO: Add higher worker value if increase API cpu and memory limit
# workers = (2 * CPU_CORES) + 1
API_WORKERS=${API_WORKERS:-1}

# Start FASTAPI / Uvicorn
uvicorn src.cqc_lem.api.main:app --host 0.0.0.0 --port $API_PORT --workers $API_WORKERS --limit-max-requests 10000 --timeout-keep-alive 30 --no-access-log