#!/bin/bash

set -o errexit
set -o nounset

# clear the selenium sessions
echo "Clearing selenium sessions"
python -c "from cqc_lem.utilities.selenium_util import clear_sessions; clear_sessions()"


# TODO: Check on the -A param here
celery -A cqc_lem.my_celery worker --loglevel=INFO
#celery --skip-checks -A cqc_lem.my_celery worker --loglevel=DEBUG -E