[theme]
base = "light"
primaryColor = "#007396" # Blue
secondaryBackgroundColor = "#B6A269" # Gold
backgroundColor = "#ffffff"  # White background
#textColor = "#B6A269"
font="sans serif"


# "#B6A269"  # CENTRAL PIEDMONT Gold
# "#636466"  # CENTRAL PIEDMONT Gray
# "#007396"  # CENTRAL PIEDMONT Blue
